(function(){
  const rawCards = [
  {"category":"Laços","difficulty":1,"code":"#include <stdio.h>\n\nint soma = 0;\nfor (int i = 1; i <= 3; i++) {\n    soma += i;\n}\nprintf(\"%d\", soma);","pseudo":"soma ← 0\nPARA i DE 1 ATÉ 3\n  soma ← soma + i\nFIM\nIMPRIMA soma","expected":"6","explanation":"O for percorre 1, 2 e 3; a soma final é 6.","initial":{"soma":0},"final":{"soma":6}},
  {"category":"Laços","difficulty":1,"code":"#include <stdio.h>\n\nint x = 0;\nwhile (x < 3) {\n    x++;\n}\nprintf(\"%d\", x);","pseudo":"x ← 0\nENQUANTO x < 3\n  x ← x + 1\nFIM\nIMPRIMA x","expected":"3","explanation":"O while incrementa x até a condição x < 3 ficar falsa.","initial":{"x":0},"final":{"x":3}},
  {"category":"Laços","difficulty":1,"code":"#include <stdio.h>\n\nfor (int i = 0; i <= 2; i++) {\n    printf(\"%d\", i);\n    if (i < 2) printf(\" \");\n}","pseudo":"PARA i DE 0 ATÉ 2\n  IMPRIMA i\nFIM","expected":"0 1 2","explanation":"O for executa com i igual a 0, 1 e 2.","initial":{"i":0},"final":{"i":2}},
  {"category":"Laços","difficulty":1,"code":"#include <stdio.h>\n\nint x = 5;\nwhile (x < 5) {\n    x++;\n}\nprintf(\"%d\", x);","pseudo":"x ← 5\nENQUANTO x < 5\n  x ← x + 1\nFIM\nIMPRIMA x","expected":"5","explanation":"A condição é falsa logo no início, então o corpo do while não executa.","initial":{"x":5},"final":{"x":5}},
  {"category":"Laços","difficulty":2,"code":"#include <stdio.h>\n\nint soma = 0;\nfor (int i = 1; i < 5; i += 2) {\n    soma += i;\n}\nprintf(\"%d\", soma);","pseudo":"soma ← 0\nPARA i COMEÇANDO EM 1, ENQUANTO i < 5, PASSO 2\n  soma ← soma + i\nFIM\nIMPRIMA soma","expected":"4","explanation":"Pegadinha de limite: a condição é i < 5, não i <= 5. O laço usa apenas 1 e 3; portanto a saída é 4.","initial":{"soma":0},"final":{"soma":4}},
  {"category":"Laços","difficulty":2,"code":"#include <stdio.h>\n\nint x = 1;\nfor (int i = 0; i < 3; i++) {\n    x *= 2;\n}\nprintf(\"%d\", x);","pseudo":"x ← 1\nREPITA 3 VEZES\n  x ← x * 2\nFIM\nIMPRIMA x","expected":"8","explanation":"x é dobrado três vezes: 1 → 2 → 4 → 8.","initial":{"x":1},"final":{"x":8}},
  {"category":"Laços","difficulty":2,"code":"#include <stdio.h>\n\nint cont = 0;\nfor (int i = 0; i < 3; i++);\n{\n    cont++;\n}\nprintf(\"%d\", cont);","pseudo":"cont ← 0\nREPITA UM LAÇO VAZIO 3 VEZES\nDEPOIS\n  cont ← cont + 1\nIMPRIMA cont","expected":"1","explanation":"Há um ponto e vírgula logo após o for. Isso transforma o corpo do laço em uma instrução vazia; o bloco seguinte executa apenas uma vez.","initial":{"cont":0},"final":{"cont":1}},
  {"category":"Laços","difficulty":2,"code":"#include <stdio.h>\n\nint x = 10;\nwhile (x > 7) {\n    x -= 2;\n}\nprintf(\"%d\", x);","pseudo":"x ← 10\nENQUANTO x > 7\n  x ← x - 2\nFIM\nIMPRIMA x","expected":"6","explanation":"x passa por 10, 8 e 6. Em 6, x > 7 é falso.","initial":{"x":10},"final":{"x":6}},
  {"category":"Laços","difficulty":3,"code":"#include <stdio.h>\n\nint soma = 0;\nfor (int i = 1; i <= 4; i++) {\n    if (i % 2 == 0) {\n        soma += i;\n    }\n}\nprintf(\"%d\", soma);","pseudo":"soma ← 0\nPARA i DE 1 ATÉ 4\n  SE i MOD 2 = 0\n    soma ← soma + i\n  FIM\nFIM\nIMPRIMA soma","expected":"6","explanation":"Somente os valores pares 2 e 4 entram na soma.","initial":{"soma":0},"final":{"soma":6}},
  {"category":"Laços","difficulty":3,"code":"#include <stdio.h>\n\nint x = 0;\nint y = 0;\nfor (int i = 1; i <= 3; i++) {\n    x++;\n    y += x;\n}\nprintf(\"%d\", y);","pseudo":"x ← 0\ny ← 0\nPARA i DE 1 ATÉ 3\n  x ← x + 1\n  y ← y + x\nFIM\nIMPRIMA y","expected":"6","explanation":"y acumula os novos valores de x: 1 + 2 + 3.","initial":{"x":0,"y":0},"final":{"x":3,"y":6}},
  {"category":"Laços","difficulty":3,"code":"#include <stdio.h>\n\nint cont = 0;\nfor (int i = 1; i <= 3; i++) {\n    for (int j = 1; j <= i; j++) {\n        cont++;\n    }\n}\nprintf(\"%d\", cont);","pseudo":"cont ← 0\nPARA i DE 1 ATÉ 3\n  PARA j DE 1 ATÉ i\n    cont ← cont + 1\n  FIM\nFIM\nIMPRIMA cont","expected":"6","explanation":"O laço interno executa 1 + 2 + 3 vezes.","initial":{"cont":0},"final":{"cont":6}},
  {"category":"Laços","difficulty":3,"code":"#include <stdio.h>\n\nint x = 1;\nwhile (x < 10) {\n    x *= 3\n}\nprintf(\"%d\", x);","pseudo":"x ← 1\nENQUANTO x < 10\n  x ← x * 3\nFIM\nIMPRIMA x","expected":"error","explanation":"O trecho não compila porque falta o ponto e vírgula após x *= 3. Quando o código não pode ser executado, a resposta correta é \"error\".","initial":{"x":1},"final":{"status":"erro de sintaxe"}},
  {"category":"Condicionais","difficulty":1,"code":"#include <stdio.h>\n\nint x = 7;\nif (x > 5) {\n    printf(\"A\");\n} else {\n    printf(\"B\");\n}","pseudo":"x ← 7\nSE x > 5\n  IMPRIMA \"A\"\nSENÃO\n  IMPRIMA \"B\"\nFIM","expected":"A","explanation":"7 é maior que 5, então o primeiro bloco é executado.","initial":{"x":7},"final":{"x":7}},
  {"category":"Condicionais","difficulty":1,"code":"#include <stdio.h>\n\nint idade = 18;\nif (idade >= 18) {\n    printf(\"maior\");\n} else {\n    printf(\"menor\");\n}","pseudo":"idade ← 18\nSE idade >= 18\n  IMPRIMA \"maior\"\nSENÃO\n  IMPRIMA \"menor\"\nFIM","expected":"maior","explanation":"O operador >= inclui o próprio valor 18.","initial":{"idade":18},"final":{"idade":18}},
  {"category":"Condicionais","difficulty":1,"code":"#include <stdio.h>\n\nint x = 4;\nif (x % 2 == 0) {\n    printf(\"par\");\n} else {\n    printf(\"ímpar\");\n}","pseudo":"x ← 4\nSE x MOD 2 = 0\n  IMPRIMA \"par\"\nSENÃO\n  IMPRIMA \"ímpar\"\nFIM","expected":"par","explanation":"4 % 2 é 0, portanto o número é par.","initial":{"x":4},"final":{"x":4}},
  {"category":"Condicionais","difficulty":1,"code":"#include <stdio.h>\n\nint nota = 6;\nif (nota >= 7) {\n    printf(\"aprovado\");\n} else {\n    printf(\"revisar\");\n}","pseudo":"nota ← 6\nSE nota >= 7\n  IMPRIMA \"aprovado\"\nSENÃO\n  IMPRIMA \"revisar\"\nFIM","expected":"revisar","explanation":"6 não satisfaz a condição nota >= 7.","initial":{"nota":6},"final":{"nota":6}},
  {"category":"Condicionais","difficulty":2,"code":"#include <stdio.h>\n\nint x = 0;\nif (x = 5) {\n    printf(\"%d\", x);\n} else {\n    printf(\"zero\");\n}","pseudo":"x ← 0\nATRIBUA 5 A x\nSE o valor da atribuição for verdadeiro\n  IMPRIMA x\nSENÃO\n  IMPRIMA \"zero\"\nFIM","expected":"5","explanation":"Pegadinha: x = 5 é atribuição, não comparação. x passa a valer 5, e 5 é tratado como verdadeiro na condição.","initial":{"x":0},"final":{"x":5}},
  {"category":"Condicionais","difficulty":2,"code":"#include <stdio.h>\n\nint x = 2;\nif (x == 1 || x == 2) {\n    printf(\"sim\");\n} else {\n    printf(\"não\");\n}","pseudo":"x ← 2\nSE x = 1 OU x = 2\n  IMPRIMA \"sim\"\nSENÃO\n  IMPRIMA \"não\"\nFIM","expected":"sim","explanation":"No operador ||, basta uma das expressões ser verdadeira.","initial":{"x":2},"final":{"x":2}},
  {"category":"Condicionais","difficulty":2,"code":"#include <stdio.h>\n\nint x = 5;\nif (!(x < 5)) {\n    printf(\"A\");\n} else {\n    printf(\"B\");\n}","pseudo":"x ← 5\nSE NÃO (x < 5)\n  IMPRIMA \"A\"\nSENÃO\n  IMPRIMA \"B\"\nFIM","expected":"A","explanation":"x < 5 é falso; !false é verdadeiro.","initial":{"x":5},"final":{"x":5}},
  {"category":"Condicionais","difficulty":2,"code":"#include <stdio.h>\n\nint x = 10;\nif (x < 5) {\n    printf(\"A\");\n} else if (x < 10) {\n    printf(\"B\");\n} else {\n    printf(\"C\");\n}","pseudo":"x ← 10\nSE x < 5\n  IMPRIMA \"A\"\nSENÃO SE x < 10\n  IMPRIMA \"B\"\nSENÃO\n  IMPRIMA \"C\"\nFIM","expected":"C","explanation":"10 não é menor que 5 nem menor que 10.","initial":{"x":10},"final":{"x":10}},
  {"category":"Condicionais","difficulty":3,"code":"#include <stdio.h>\n\nint x = 5;\nif (x > 0)\n    if (x < 3)\n        printf(\"A\");\n    else\n        printf(\"B\");\nelse\n    printf(\"C\");","pseudo":"x ← 5\nSE x > 0\n  SE x < 3\n    IMPRIMA \"A\"\n  SENÃO\n    IMPRIMA \"B\"\nSENÃO\n  IMPRIMA \"C\"","expected":"B","explanation":"Sem chaves, o else é associado ao if mais próximo ainda sem else. Como x > 0 é verdadeiro e x < 3 é falso, imprime B.","initial":{"x":5},"final":{"x":5}},
  {"category":"Condicionais","difficulty":3,"code":"#include <stdio.h>\n\nint x = 6;\nif (x > 0) {\n    if (x % 2 == 0) {\n        printf(\"positivo par\");\n    } else {\n        printf(\"positivo ímpar\");\n    }\n} else {\n    printf(\"não positivo\");\n}","pseudo":"x ← 6\nSE x > 0\n  SE x MOD 2 = 0\n    IMPRIMA \"positivo par\"\n  SENÃO\n    IMPRIMA \"positivo ímpar\"\n  FIM\nSENÃO\n  IMPRIMA \"não positivo\"\nFIM","expected":"positivo par","explanation":"x é positivo e também é divisível por 2.","initial":{"x":6},"final":{"x":6}},
  {"category":"Condicionais","difficulty":3,"code":"#include <stdio.h>\n\nint x = 3;\nint y = 4;\nif (x > 2 && (y < 4 || x + y == 7)) {\n    printf(\"A\");\n} else {\n    printf(\"B\");\n}","pseudo":"x ← 3\ny ← 4\nSE x > 2 E (y < 4 OU x + y = 7)\n  IMPRIMA \"A\"\nSENÃO\n  IMPRIMA \"B\"\nFIM","expected":"A","explanation":"x > 2 é verdadeiro e x + y == 7 também é verdadeiro.","initial":{"x":3,"y":4},"final":{"resultado":true}},
  {"category":"Condicionais","difficulty":3,"code":"#include <stdio.h>\n\nint x = 4;\nif (y > x) {\n    printf(\"Y\");\n} else {\n    printf(\"X\");\n}","pseudo":"x ← 4\nSE y > x\n  IMPRIMA \"Y\"\nSENÃO\n  IMPRIMA \"X\"\nFIM","expected":"error","explanation":"A variável y nunca foi declarada. O compilador não consegue resolver esse identificador, então a resposta é \"error\".","initial":{"x":4},"final":{"status":"variável y não declarada"}},
  {"category":"Tipos e valores","difficulty":1,"code":"#include <stdio.h>\n\nint a = 7;\nint b = 2;\nprintf(\"%d\", a / b);","pseudo":"a ← 7\nb ← 2\nIMPRIMA a DIV b","expected":"3","explanation":"Como a e b são int, a divisão inteira descarta a parte fracionária.","initial":{"a":7,"b":2},"final":{"resultado":3}},
  {"category":"Tipos e valores","difficulty":1,"code":"#include <stdio.h>\n\nfloat resultado = 7 / 2;\nprintf(\"%.1f\", resultado);","pseudo":"resultado ← 7 DIVIDIDO POR 2 USANDO INTEIROS\nCONVERTA O RESULTADO PARA REAL\nIMPRIMA resultado COM 1 CASA DECIMAL","expected":"3.0","explanation":"7 e 2 são inteiros, então a divisão acontece primeiro como divisão inteira: 7 / 2 = 3. Só depois 3 é armazenado no float, virando 3.0.","initial":{},"final":{"resultado":3.0}},
  {"category":"Tipos e valores","difficulty":1,"code":"#include <stdio.h>\n\nchar texto[] = \"10\";\nint numero = 5;\nchar resultado[10];\nsprintf(resultado, \"%s%d\", texto, numero);\nprintf(\"%s\", resultado);","pseudo":"texto ← \"10\"\nnumero ← 5\nresultado ← FORMATAR texto E numero\nIMPRIMA resultado","expected":"105","explanation":"sprintf, da biblioteca <stdio.h>, monta o texto juntando \"10\" e o número 5; depois printf exibe 105.","initial":{"texto":"10","numero":5},"final":{"resultado":"105"}},
  {"category":"Tipos e valores","difficulty":1,"code":"#include <stdio.h>\n\nint x = 5;\ndouble y = 5.0;\nprintf(\"%s\", x == y ? \"verdadeiro\" : \"falso\");","pseudo":"x ← 5\ny ← 5.0\nIMPRIMA x = y","expected":"verdadeiro","explanation":"Na comparação, os valores numéricos 5 e 5.0 são equivalentes.","initial":{"x":5,"y":5.0},"final":{"resultado":true}},
  {"category":"Tipos e valores","difficulty":2,"code":"#include <stdio.h>\n\nint x = 9;\nprintf(\"%d\", x % 4);","pseudo":"x ← 9\nIMPRIMA x MOD 4","expected":"1","explanation":"O operador % retorna o resto da divisão inteira.","initial":{"x":9},"final":{"resultado":1}},
  {"category":"Tipos e valores","difficulty":2,"code":"#include <stdio.h>\n\nint x = -7;\nint absoluto = x < 0 ? -x : x;\nprintf(\"%d\", absoluto);","pseudo":"x ← -7\nIMPRIMA ABS(x)","expected":"7","explanation":"O operador condicional calcula o valor absoluto sem depender de outra biblioteca; -7 vira 7.","initial":{"x":-7},"final":{"resultado":7}},
  {"category":"Tipos e valores","difficulty":2,"code":"#include <stdio.h>\n\nint x = 3;\nint y = x++;\nprintf(\"%d %d\", x, y);","pseudo":"x ← 3\ny ← valor atual de x\nDEPOIS x ← x + 1\nIMPRIMA x E y","expected":"4 3","explanation":"x++ é pós-incremento: y recebe o valor antigo de x (3) e somente depois x passa a valer 4.","initial":{"x":3},"final":{"x":4,"y":3}},
  {"category":"Tipos e valores","difficulty":2,"code":"#include <stdio.h>\n\nint a = 2;\nint b = 3;\nchar c[] = \"4\";\nint valor;\nsscanf(c, \"%d\", &valor);\nprintf(\"%d\", a + b + valor);","pseudo":"a ← 2\nb ← 3\nc ← \"4\"\nvalor ← LER_INTEIRO(c)\nIMPRIMA a + b + valor","expected":"9","explanation":"sscanf, da biblioteca <stdio.h>, lê o texto \"4\" como inteiro; então 2 + 3 + 4 = 9.","initial":{"a":2,"b":3,"c":"4"},"final":{"resultado":9}},
  {"category":"Tipos e valores","difficulty":3,"code":"#include <stdio.h>\n\ndouble x = 0.1 + 0.2;\nif (x == 0.3) {\n    printf(\"igual\");\n} else {\n    printf(\"pode diferir\");\n}","pseudo":"x ← 0.1 + 0.2\nSE x = 0.3\n  IMPRIMA \"igual\"\nSENÃO\n  IMPRIMA \"pode diferir\"\nFIM","expected":"pode diferir","explanation":"Números de ponto flutuante podem não representar 0.1, 0.2 e 0.3 exatamente em binário.","initial":{"x":"aprox. 0.30000000000000004"},"final":{"comparacao":false}},
  {"category":"Tipos e valores","difficulty":3,"code":"#include <stdio.h>\n\nint a = 5;\nint b = 2;\nint x = (a / b) * b;\nprintf(\"%d\", x);","pseudo":"a ← 5\nb ← 2\nx ← (a DIV b) * b\nIMPRIMA x","expected":"4","explanation":"a / b é uma divisão inteira: 5 / 2 = 2; depois 2 * 2 = 4.","initial":{"a":5,"b":2},"final":{"x":4}},
  {"category":"Tipos e valores","difficulty":3,"code":"#include <stdio.h>\n\nchar x[] = \"3\";\nint valor;\nsscanf(x, \"%d\", &valor);\nint y = valor + 2;\nchar texto[10];\nsprintf(texto, \"%d!\", y);\nprintf(\"%s\", texto);","pseudo":"x ← \"3\"\nvalor ← LER_INTEIRO(x)\ny ← valor + 2\ntexto ← FORMATAR y + \"!\"\nIMPRIMA texto","expected":"5!","explanation":"sscanf converte \"3\" para inteiro; depois sprintf formata o resultado 5 junto com o caractere !.","initial":{"x":"3"},"final":{"y":5}},
  {"category":"Tipos e valores","difficulty":3,"code":"#include <stdio.h>\n\nint x = \"5\";\nprintf(\"%d\", x);","pseudo":"TENTE armazenar o texto \"5\" diretamente em uma variável inteira x\nIMPRIMA x","expected":"error","explanation":"Em C++, um literal de texto como \"5\" não pode ser convertido implicitamente para int. O trecho não compila; responda \"error\".","initial":{},"final":{"status":"conversão inválida"}},
  {"category":"Escopo e referência","difficulty":1,"code":"#include <stdio.h>\n\nint x = 10;\n{\n    int x_local = 3;\n    printf(\"%d \", x_local);\n}\nprintf(\"%d\", x);","pseudo":"x ← 10\nINÍCIO_BLOCO\n  x_local ← 3\n  IMPRIMA x_local\nFIM_BLOCO\nIMPRIMA x","expected":"3 10","explanation":"x_local existe apenas dentro do bloco e não altera x.","initial":{"x":10},"final":{"x":10}},
  {"category":"Escopo e referência","difficulty":1,"code":"#include <stdio.h>\n\nint lista[2] = {1, 2};\nprintf(\"%d\", lista[0]);","pseudo":"lista ← [1, 2]\nIMPRIMA lista[0]","expected":"1","explanation":"Em C++, o primeiro elemento de um array tem índice 0.","initial":{"lista":[1,2]},"final":{"resultado":1}},
  {"category":"Escopo e referência","difficulty":1,"code":"#include <stdio.h>\n\nint lista[2] = {1, 2};\nlista[1] = 9;\nprintf(\"[%d, %d]\", lista[0], lista[1]);","pseudo":"lista ← [1, 2]\nlista[1] ← 9\nIMPRIMA lista","expected":"[1, 9]","explanation":"lista[1] representa o segundo elemento do array.","initial":{"lista":[1,2]},"final":{"lista":[1,9]}},
  {"category":"Escopo e referência","difficulty":1,"code":"#include <stdio.h>\n\nint x = 2;\n{\n    int y = x + 3;\n}\nprintf(\"%d\", y);","pseudo":"x ← 2\nINÍCIO_BLOCO\n  y ← x + 3\nFIM_BLOCO\nTENTE IMPRIMIR y","expected":"error","explanation":"y existe somente dentro do bloco entre chaves. Fora dele, y está fora de escopo e o trecho não compila. A resposta é \"error\".","initial":{"x":2},"final":{"status":"y fora de escopo"}},
  {"category":"Escopo e referência","difficulty":2,"code":"#include <stdio.h>\n\nint a[2] = {1, 2};\nint (&b)[2] = a;\nb[0] = 9;\nprintf(\"[%d, %d]\", a[0], a[1]);","pseudo":"a ← [1, 2]\nb REFERENCIA a\nb[0] ← 9\nIMPRIMA a","expected":"[9, 2]","explanation":"b é uma referência para o mesmo array a; alterar b altera a.","initial":{"a":[1,2]},"final":{"a":[9,2],"b":"referência de a"}},
  {"category":"Escopo e referência","difficulty":2,"code":"#include <stdio.h>\n\nint x = 1;\n{\n    int x = 5;\n    printf(\"%d \", x);\n}\nprintf(\"%d\", x);","pseudo":"x externo ← 1\nINÍCIO_BLOCO\n  crie OUTRO x ← 5\n  IMPRIMA x interno\nFIM_BLOCO\nIMPRIMA x externo","expected":"5 1","explanation":"O int x = 5 cria uma nova variável que sombreia o x externo. Dentro do bloco imprime 5; fora dele, o x original continua valendo 1.","initial":{"x externo":1},"final":{"x externo":1,"x interno":5}},
  {"category":"Escopo e referência","difficulty":2,"code":"#include <stdio.h>\n\nint lista[3] = {2, 4, 6};\nfor (int i = 0; i < 3; i++) {\n    lista[i]++;\n}\nprintf(\"[%d, %d, %d]\", lista[0], lista[1], lista[2]);","pseudo":"lista ← [2, 4, 6]\nPARA i DE 0 ATÉ 2\n  lista[i] ← lista[i] + 1\nFIM\nIMPRIMA lista","expected":"[3, 5, 7]","explanation":"Cada posição do array é incrementada uma vez.","initial":{"lista":[2,4,6]},"final":{"lista":[3,5,7]}},
  {"category":"Escopo e referência","difficulty":2,"code":"#include <stdio.h>\n\nint x = 4;\n{\n    int x = 9;\n    printf(\"%d \", x);\n}\nprintf(\"%d\", x);","pseudo":"x ← 4\nINÍCIO_BLOCO\n  DECLARE x ← 9\n  IMPRIMA x\nFIM_BLOCO\nIMPRIMA x","expected":"9 4","explanation":"O x interno sombreia o x externo apenas dentro do bloco.","initial":{"x_externo":4},"final":{"x_interno":9,"x_externo":4}},
  {"category":"Escopo e referência","difficulty":3,"code":"#include <stdio.h>\n\nint a[2] = {1, 2};\nint b[2] = {a[0], a[1]};\nb[0] = 7;\nprintf(\"[%d, %d] \", a[0], a[1]);\nprintf(\"[%d, %d]\", b[0], b[1]);","pseudo":"a ← [1, 2]\nb ← CÓPIA(a)\nb[0] ← 7\nIMPRIMA a\nIMPRIMA b","expected":"[1, 2] [7, 2]","explanation":"b é criado como uma cópia dos valores de a. Alterar b[0] não modifica o array a.","initial":{"a":[1,2]},"final":{"a":[1,2],"b":[7,2]}},
  {"category":"Escopo e referência","difficulty":3,"code":"#include <stdio.h>\n\nint x = 1;\nfor (int i = 1; i <= 2; i++) {\n    int x = i * 10;\n}\nprintf(\"%d\", x);","pseudo":"x ← 1\nPARA i DE 1 ATÉ 2\n  DECLARE x ← i * 10\nFIM\nIMPRIMA x","expected":"1","explanation":"O x declarado dentro do laço é local ao bloco e não altera o x externo.","initial":{"x_externo":1},"final":{"x_externo":1}},
  {"category":"Escopo e referência","difficulty":3,"code":"#include <stdio.h>\n\nint a[1] = {1};\nint (&b)[1] = a;\nint (&c)[1] = b;\nc[0] = 8;\nprintf(\"%d\", a[0] + b[0] + c[0]);","pseudo":"a ← [1]\nb REFERENCIA a\nc REFERENCIA b\nc[0] ← 8\nIMPRIMA a[0] + b[0] + c[0]","expected":"24","explanation":"a, b e c se referem ao mesmo array; depois de c[0] = 8, os três acessos retornam 8.","initial":{"a":[1]},"final":{"a":[8],"b":"ref(a)","c":"ref(a)"}},
  {"category":"Escopo e referência","difficulty":3,"code":"#include <stdio.h>\n\nint x = 2;\n{\n    int localX = x + 3;\n    printf(\"%d \", localX);\n}\nprintf(\"%d\", x);","pseudo":"x ← 2\nINÍCIO_BLOCO\n  localX ← x + 3\n  IMPRIMA localX\nFIM_BLOCO\nIMPRIMA x","expected":"5 2","explanation":"localX usa o valor de x, mas é uma variável diferente e restrita ao bloco.","initial":{"x":2},"final":{"x":2,"localX":5}},
  {"category":"Funções","difficulty":1,"code":"#include <stdio.h>\n\nint dobro(int x) {\n    return x * 2;\n}\nprintf(\"%d\", dobro(4));","pseudo":"FUNÇÃO dobro(x)\n  RETORNE x * 2\nFIM\nIMPRIMA dobro(4)","expected":"8","explanation":"A função recebe 4 e retorna 4 * 2.","initial":{"x":4},"final":{"retorno":8}},
  {"category":"Funções","difficulty":1,"code":"#include <stdio.h>\n\nint soma(int a, int b) {\n    return a - b;\n}\nint x = soma(2, 3);\nprintf(\"%d\", x);","pseudo":"FUNÇÃO chamada soma(a, b)\n  RETORNE a - b\nFIM\nx ← soma(2, 3)\nIMPRIMA x","expected":"-1","explanation":"O nome da função sugere soma, mas o código faz subtração. O jogador deve seguir o código real: 2 - 3 = -1.","initial":{"a":2,"b":3},"final":{"x":-1}},
  {"category":"Funções","difficulty":1,"code":"#include <stdio.h>\n\nconst char* saudacao() {\n    return \"oi\";\n}\nprintf(\"%s\", saudacao());","pseudo":"FUNÇÃO saudacao()\n  RETORNE \"oi\"\nFIM\nIMPRIMA saudacao()","expected":"oi","explanation":"A função não recebe parâmetros e retorna um ponteiro para o texto literal \"oi\", exibido com printf.","initial":{},"final":{"retorno":"oi"}},
  {"category":"Funções","difficulty":1,"code":"#include <stdio.h>\n\nint identidade(int x) {\n    return x;\n}\nprintf(\"%d\", identidade(7));","pseudo":"FUNÇÃO identidade(x)\n  RETORNE x\nFIM\nIMPRIMA identidade(7)","expected":"7","explanation":"A função simplesmente devolve o valor recebido.","initial":{"x":7},"final":{"retorno":7}},
  {"category":"Funções","difficulty":2,"code":"#include <stdio.h>\n\nint maior(int a, int b) {\n    if (a > b) return a;\n    return b;\n}\nprintf(\"%d\", maior(3, 5));","pseudo":"FUNÇÃO maior(a, b)\n  SE a > b\n    RETORNE a\n  SENÃO\n    RETORNE b\n  FIM\nFIM\nIMPRIMA maior(3, 5)","expected":"5","explanation":"Como 3 > 5 é falso, a função retorna b, que vale 5.","initial":{"a":3,"b":5},"final":{"retorno":5}},
  {"category":"Funções","difficulty":2,"code":"#include <stdio.h>\n\nint inc(int x) {\n    x++;\n    return x;\n}\nint a = 4;\nint b = inc(a);\nprintf(\"%d %d\", a, b);","pseudo":"FUNÇÃO inc(x)\n  x ← x + 1\n  RETORNE x\nFIM\na ← 4\nb ← inc(a)\nIMPRIMA a\nIMPRIMA b","expected":"4 5","explanation":"x é recebido por valor. Alterar x dentro da função não modifica a variável a.","initial":{"a":4},"final":{"a":4,"b":5}},
  {"category":"Funções","difficulty":2,"code":"#include <stdio.h>\n\nint somaAte(int n) {\n    int total = 0;\n    for (int i = 1; i <= n; i++) {\n        total += i;\n    }\n    return total;\n}\nprintf(\"%d\", somaAte(4));","pseudo":"FUNÇÃO somaAte(n)\n  total ← 0\n  PARA i DE 1 ATÉ n\n    total ← total + i\n  FIM\n  RETORNE total\nFIM\nIMPRIMA somaAte(4)","expected":"10","explanation":"A função calcula 1 + 2 + 3 + 4.","initial":{"n":4},"final":{"total":10,"retorno":10}},
  {"category":"Funções","difficulty":2,"code":"#include <stdio.h>\n\nvoid mostraDobro(int x) {\n    printf(\"%d\", x * 2);\n}\nmostraDobro(3);","pseudo":"PROCEDIMENTO mostraDobro(x)\n  IMPRIMA x * 2\nFIM\nCHAME mostraDobro(3)","expected":"6","explanation":"Uma função void não retorna valor; neste caso ela imprime diretamente 3 * 2.","initial":{"x":3},"final":{"saida":6}},
  {"category":"Funções","difficulty":3,"code":"#include <stdio.h>\n\nint fatorial(int n) {\n    if (n <= 1) return 0;\n    return n * fatorial(n - 1);\n}\nprintf(\"%d\", fatorial(4));","pseudo":"FUNÇÃO fatorial(n)\n  SE n <= 1\n    RETORNE 0\n  FIM\n  RETORNE n * fatorial(n - 1)\nFIM\nIMPRIMA fatorial(4)","expected":"0","explanation":"Há um erro de lógica no caso-base: ele retorna 0 em vez de 1. Como toda multiplicação termina multiplicando por 0, o resultado final é 0.","initial":{"n":4},"final":{"retorno":0}},
  {"category":"Funções","difficulty":3,"code":"#include <stdio.h>\n\nint fib(int n) {\n    if (n <= 1) return n;\n    return fib(n - 1) + fibb(n - 2);\n}\nprintf(\"%d\", fib(5));","pseudo":"FUNÇÃO fib(n)\n  SE n <= 1\n    RETORNE n\n  FIM\n  RETORNE fib(n-1) + CHAMADA_INEXISTENTE(n-2)\nFIM\nIMPRIMA fib(5)","expected":"error","explanation":"A função fibb não foi declarada. É um erro de nome na chamada recursiva, portanto o trecho não compila e a resposta correta é \"error\".","initial":{"n":5},"final":{"status":"função fibb não declarada"}},
  {"category":"Funções","difficulty":3,"code":"#include <stdio.h>\n\nvoid altera(int (&lista)[2]) {\n    lista[0] = 9;\n}\nint a[2] = {1, 2};\naltera(a);\nprintf(\"[%d, %d]\", a[0], a[1]);","pseudo":"PROCEDIMENTO altera(lista POR REFERÊNCIA)\n  lista[0] ← 9\nFIM\na ← [1, 2]\nCHAME altera(a)\nIMPRIMA a","expected":"[9, 2]","explanation":"O parâmetro é uma referência para um array de dois inteiros, então a função modifica o array original.","initial":{"a":[1,2]},"final":{"a":[9,2]}},
  {"category":"Funções","difficulty":3,"code":"#include <stdio.h>\n\nint misterio(int n) {\n    if (n == 0) return 0;\n    return 1 + misterio(n - 1);\n}\nprintf(\"%d\", misterio(3));","pseudo":"FUNÇÃO misterio(n)\n  SE n = 0\n    RETORNE 0\n  FIM\n  RETORNE 1 + misterio(n - 1)\nFIM\nIMPRIMA misterio(3)","expected":"3","explanation":"A função soma 1 a cada chamada até n chegar a zero.","initial":{"n":3},"final":{"retorno":3}}
  ];

  const buildSteps = (card) => {
    const lines = card.code.split('\n');
    const outputLine = (() => {
      for (let i = lines.length - 1; i >= 0; i--) {
        if (/^\s*printf\s*\(/.test(lines[i])) return i + 1;
      }
      return lines.length;
    })();

    const middleLine = Math.max(1, Math.min(outputLine - 1, Math.ceil(lines.length / 2)));
    const isError = String(card.expected).toLowerCase() === 'error';

    if (isError) {
      return [
        { line: 1, vars: card.initial || {}, output: '' },
        { line: middleLine, vars: { status: 'analisando o trecho...' }, output: '' },
        { line: outputLine, vars: card.final || { status: 'erro detectado' }, output: 'error' }
      ];
    }

    return [
      { line: 1, vars: card.initial || {}, output: '' },
      { line: middleLine, vars: card.final || card.initial || {}, output: '' },
      { line: outputLine, vars: card.final || {}, output: card.expected }
    ];
  };

  window.RASTREIO_CARDS = rawCards.map((card, index) => ({
    id: index + 1,
    category: card.category,
    difficulty: card.difficulty,
    language: 'C++',
    code: card.code,
    pseudo: card.pseudo,
    expected: String(card.expected),
    explanation: card.explanation,
    steps: buildSteps(card)
  }));
})();
